set -g mouse on
setw -g mode-keys vi
unbind-key -T copy-mode-vi Space
unbind-key -T copy-mode-vi v

bind-key -T copy-mode-vi v send-keys -X begin-selection     # Begin selection in copy mode.
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle  # Begin selection in copy mode.
bind-key -T copy-mode-vi y send-keys -X copy-selection      # Yank selection in copy mode.

unbind-key q
unbind-key Q
bind q confirm kill-window
bind Q confirm kill-session
